# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

FactoryGirl.create(:user) unless User.where(email: "test@dreamyourweb.nl")

FactoryGirl.create(:aspect, title: "Mogelijkheden", answer_type: "mc")
FactoryGirl.create(:aspect, title: "Beveiliging", answer_type: "mc")
FactoryGirl.create(:aspect, title: "Continuiteit", answer_type: "mc")
FactoryGirl.create(:aspect, title: "Kosten", answer_type: "cash")

FactoryGirl.create(:indicator, title: "Mobiele Werkplek", description: "Overal en altijd bij uw gegevens kunnen. Als professional zit u nooit stil en dus is het belangrijk dat uw werkomgeving met u meereist. Deze indicator geeft aan hoe goed u bent ingespeeld op het thuis- of op locatie werken. Overal dezelfde werkomgeving en altijd toegang tot uw gegevens. Dat is het streven voor u en uw personeel.", example: %Q(Hoe zou het zijn om 's ochtends uitgerust op te staan, de kinderen op het gemak naar school te brengen, om daarna de eerste e-mail van de dag in alle rust te beantwoorden? Aan het eind van de dag doe je nog even een boodschap in de supermarkt, en de wachttijd in de rij voor de kassa benut je om een aantal korte e-mails te beantwoorden met je smartphone. Dat helpt om straks weer tijd over te houden voor andere zaken.))
FactoryGirl.create(:indicator, title: "Apparaat Synchronisatie", description: "Als professional kunt u het zich niet veroorloven om kansen te missen. U zit overal meteen bovenop en daar heeft u verschillende (mobiele) apparaten voor. Even snel een vervolg-afspraak maken gaat niet als uw gegevens verspreid staan. Daarom is het belangrijk gegevens te synchroniseren over al uw apparaten.", example: "Mijn agenda deel ik met mijn collega en hij zijn agenda met mij. Daardoor weten we - wanneer het nodig is - welke afspraken de ander heeft. Geen gedoe meer met een keer per week de agenda's naast elkaar leggen. Je hebt immers toegang tot elkaars agenda: waar je ook bent en wanneer je wilt. Verrassend praktisch als je allebei nogal eens op pad bent.")
FactoryGirl.create(:indicator, title: "Controle op ICT-beheer", description: "Een klant die u moet vertellen dat uw systeem niet werkt, dat is wel het laatste wat u wilt. Daarom is het belangrijk om op elk moment te weten hoe uw systeem ervoor staat. Het is belangrijk om altijd en overal inzicht te hebben in de kwaliteit en kosten van uw systeem. Zo weet u als eerste waar de fout zit en kunt u van te voren inspelen op kritieke gebeurtenissen, terwijl anderen achter de feiten aanlopen.", example: %Q(Een aantal weken geleden ontving onze helpdesk een melding dat een van de harde schijven van een server corrupt was. Dezelfde dag is een harde schijf uit voorraad geleverd en geinstalleerd. Dankzij deze manier van pro-actieve monitoring wordt voorkomen dat er gegevens verloren gaan.))
FactoryGirl.create(:indicator, title: "Andere mogelijkheden", description: "Niemand weet precies wat de toekomst over een aantal jaar gaat brengen, maar dat wil niet zeggen dat u er niet op voorbereid kunt zijn. Daarom is het goed om uw schaalbaarheid en nieuwe technische mogelijkheden in het oog te houden. Zo kunt u zich nu al voorbereiden op een gastnetwerk, of bijvoorbeeld het printen via uw iPhone of iPad.", example: "Sterknetwerk denkt veelal mee met de verwachte en de beoogde groei van haar klanten. Een aantal van onze klanten zijn hierdoor in staat geweest binnen een aantal jaar te groeien van 5 naar 50 medewerkers. Zonder dat ze daarbij zijn geremd in hun technische mogelijkheden en altijd voorop lopen met technische ontwikkeling. Dat heeft hen er toe in staat gesteld om te groeien tot voorloper binnen hun branche.")

Question.create!(title: "Heeft u overal en altijd toegang tot uw e-mail en agenda (mobiele telefoon / webmail)?", indicator: Indicator.where(title: "Apparaat synchronisatie").first, aspect: Aspect.where(title: "Mogelijkheden").first)