# encoding: utf-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

FactoryGirl.create(:user) if User.where(email: "test@dreamyourweb.nl").first.nil?

FactoryGirl.create(:aspect, title: "Mogelijkheden", answer_type: "mc")
FactoryGirl.create(:aspect, title: "Beveiliging", answer_type: "mc")
FactoryGirl.create(:aspect, title: "Continuiteit", answer_type: "mc")
FactoryGirl.create(:aspect, title: "Kosten", answer_type: "cash")

FactoryGirl.create(:indicator, title: "Mobiele Werkplek", image_name: "overalonline.png", description: "Overal en altijd bij uw gegevens kunnen. Als professional zit u nooit stil en dus is het belangrijk dat uw werkomgeving met u meereist. Deze indicator geeft aan hoe goed u bent ingespeeld op het thuis- of op locatie werken. Overal dezelfde werkomgeving en altijd toegang tot uw gegevens. Dat is het streven voor u en uw personeel.", example: %Q(Hoe zou het zijn om 's ochtends uitgerust op te staan, de kinderen op het gemak naar school te brengen, om daarna de eerste e-mail van de dag in alle rust te beantwoorden? Aan het eind van de dag doe je nog even een boodschap in de supermarkt, en de wachttijd in de rij voor de kassa benut je om een aantal korte e-mails te beantwoorden met je smartphone. Dat helpt om straks weer tijd over te houden voor andere zaken.))
FactoryGirl.create(:indicator, title: "Apparaat Synchronisatie", image_name: "apparaatsync.png", description: "Als professional kunt u het zich niet veroorloven om kansen te missen. U zit overal meteen bovenop en daar heeft u verschillende (mobiele) apparaten voor. Even snel een vervolg-afspraak maken gaat niet als uw gegevens verspreid staan. Daarom is het belangrijk gegevens te synchroniseren over al uw apparaten.", example: "Mijn agenda deel ik met mijn collega en hij zijn agenda met mij. Daardoor weten we - wanneer het nodig is - welke afspraken de ander heeft. Geen gedoe meer met een keer per week de agenda's naast elkaar leggen. Je hebt immers toegang tot elkaars agenda: waar je ook bent en wanneer je wilt. Verrassend praktisch als je allebei nogal eens op pad bent.")
FactoryGirl.create(:indicator, title: "Controle op ICT-beheer", image_name: "controleopIT.png", description: "Een klant die u moet vertellen dat uw systeem niet werkt, dat is wel het laatste wat u wilt. Daarom is het belangrijk om op elk moment te weten hoe uw systeem ervoor staat. Het is belangrijk om altijd en overal inzicht te hebben in de kwaliteit en kosten van uw systeem. Zo weet u als eerste waar de fout zit en kunt u van te voren inspelen op kritieke gebeurtenissen, terwijl anderen achter de feiten aanlopen.", example: %Q(Een aantal weken geleden ontving onze helpdesk een melding dat één  van de harde schijven van een server corrupt was. Dezelfde dag is een harde schijf uit voorraad geleverd en geïnstalleerd. Dankzij deze manier van pro-actieve monitoring wordt voorkomen dat er gegevens verloren gaan.))
FactoryGirl.create(:indicator, title: "Andere mogelijkheden", image_name: "anderemogelijkheden.png", description: "Niemand weet precies wat de toekomst over een aantal jaar gaat brengen, maar dat wil niet zeggen dat u er niet op voorbereid kunt zijn. Daarom is het goed om uw schaalbaarheid en nieuwe technische mogelijkheden in het oog te houden. Zo kunt u zich nu al voorbereiden op een gastnetwerk, of bijvoorbeeld het printen via uw iPhone of iPad.", example: "Sterknetwerk denkt veelal mee met de verwachte en de beoogde groei van haar klanten. Een aantal van onze klanten zijn hierdoor in staat geweest binnen een aantal jaar te groeien van 5 naar 50 medewerkers. Zonder dat ze daarbij zijn geremd in hun technische mogelijkheden en altijd voorop lopen met technische ontwikkeling. Dat heeft hen er toe in staat gesteld om te groeien tot voorloper binnen hun branche.")

FactoryGirl.create(:indicator, title: "Databescherming", image_name: "virusscanner.png", description: "De meeste organisaties hebben kritische data verspreid staan over verschillende servers binnen de organisatie waardoor IT afdelingen geen of weinig inzage hebben in: Wie creeert de data; Wie is de eigenaar van de data; Wie heeft toegang tot die data en wie heeft wanneer de data daadwerkelijk gebruikt. Wanneer u dit inzichtelijk heeft kunt u bepalen wie wel en wie geen toegang heeft tot bepaalde data.", example: "Het laatste wat je wil is dat een medewerker met vertrouwelijke data de deur uit loopt. We zouden niet de eerste zijn waarvan de data op straat beland. Door samen een duidelijke analyse van de data gemaakt te hebben, en hier de beveiliging op aan te passen. Is er voorkomen dat dit in de verkeerde handen terecht kon komen.")
FactoryGirl.create(:indicator, title: "Spam filter", image_name: "spamfilter.png", description: "Bijna 90% van alle verzonden e-mail is spam. Dit is niet alleen hinderlijk, maar neemt ook onnodig productieve tijd van werknemers binnen organisaties in beslag. De steeds grotere wordende stroom van spam-berichten vraagt daarnaast veel servercapaciteit. Dit zorgt voor extra kosten en kan ten koste gaan van de snelheid van het mailverkeer.", example: "Ook wij weten dat spam nooit helemaal te voorkomen is, maar met de juiste maatregelen is de overlast wel tot een minimum te beperken. Door gebruik te maken van de spamfilter is het inderdaad beperkt tot een minimum. En de tijd die het kostte om de spamberichten te verwijderen kunnen we nu besteden aan nuttige zaken.")
FactoryGirl.create(:indicator, title: "Tokens", image_name: "token.png", description: "De zwakste schakel bij toegangsbeveiliging is de mens: vaste wachtwoorden staan bovenaan de lijst van beveilingsproblemen. Dat probleem kan opgelost worden door gebruik te maken van tokens, een apparaat wat telkens een andere code genereert, welke u gebruikt icm uw wachtwoord.", example: "Binnen onze organisatie hebben we verschillende oplossing geprobeerd, om onze omgeving goed te beveiligen. Maar vaak had men uiteindelijk toch nog de gele briefjes nodig om de wachtwoorden te onthouden. Met de tokens is dit beveiligingsrisico verleden tijd, het security gat is hiermee gedicht.")
FactoryGirl.create(:indicator, title: "Open poorten", image_name: "openpoorten.png", description: "Uw netwerk is niet alleen kwetsbaar voor hackers, ook virussen, trojaanse paarden en wormen kunnen u veel schade berokkenen. Een firewall is daarom noodzakelijk om de deuren (poorten) naar en van het internet te beheren. Door poorten dicht te zetten die u doorgaans toch niet gebruikt, is uw computer beter beschermd tegen computerinbraak.", example: "Neem als voorbeeld je huis, je hebt een voor- en een achterdeur. Als je de achterdeur nooit gebruikt kun je deze beter blokkeren, waarom? Het is een potentieel risico voor een dief om binnen te komen. Met een firewall doen we hetzelfde , we blokkeren elke poort die we niet nodig hebben.")

FactoryGirl.create(:indicator, title: "Backup", image_name: "back-up.png", description: "Aan computers wordt vandaag de dag steeds meer informatie toevertrouwd. Trouwfoto's, zakelijke documenten, belangrijke e-mails... Hoe betrouwbaar een computer vandaag de dag ook is, er is een kans dat de harde schijf defect raakt. Als dat gebeurt bent u een gedeelte van of zelfs al uw data kwijt. Daarom is het belangrijk om te allen tijde over een goede back-up te beschikken. Zodat u uw bestanden binnen no-time weer bij de hand heeft.", example: "Een brand in een van onze kantoren had funest kunnen zijn voor onze bedrijfsvoering. Tot voor kort was de back-up van de locatie namelijk niet gekoppeld aan het internet maar aan een externe harde schijf. Bij de brand was die externe harde schrijf vernietigd, maar door de online back-up waren we letterlijk uit de brand.")
FactoryGirl.create(:indicator, title: "Defecte hardware", image_name: "defectehardware.png", description: 'Bij hardware defecten valt te denken aan een gescheurd scherm, kapotte harde schijf of een toetsenbord dat niet meer werkt. Maar ook essentiële onderdelen van fysieke servers kunnen defect raken. Het is daarom van groot belang om ervoor te zorgen dat u altijd een snelle oplossing/vervanging achter de hand heeft.', example: 'Een aantal weken geleden ontving onze helpdesk een melding dat één van de harde schijven van een server corrupt was. Dezelfde dag is een harde schijf uit voorraad geleverd en geïnstalleerd. Dankzij deze manier van pro-actieve monitoring wordt voorkomen dat er gegevens verloren gaan.')
FactoryGirl.create(:indicator, title: "Serviceaanvragen", image_name: "helpdesk.png", description: "Wanneer het onverhoopt voorkomt dat er iets met het netwerk of een werkplek mis is, dan dient u zo snel mogelijk geholpen te worden. Elke minuut offline heeft immers gevolgen voor uw bedrijfsvoering. En om dit zo spoedig en effectief mogelijk te laten verlopen wilt u deze problemen het liefst bij professionals neerleggen.", example: "Wat ons vooral bevalt is dat de mensen echt meedenken en ons het gevoel geven dat ze er voor  ons zijn. En dan het gemak dat we ervan hebben; als een van ons belt dat er iets is dan komen ze direct opdraven. Pas nog met een laptop die kapot ging, het was zo geregeld.")
FactoryGirl.create(:indicator, title: "Stabiel netwerk", image_name: "stabielnetwerk.png", description: "Naast een correct ingerichte werkplek is een stabiele verbinding met het Internet van groot belang, uw digitale communicatie loopt via dit medium. Een kleine onderneming met 5 medewerkers heeft vaak een hele andere behoefte aan een internet verbinding als een organisatie met 50 medewerkers. Het is dus daarom belangrijk om voor uw onderneming de juiste internetverbinding te kiezen.", example: "Na een paar jaar sukkelen met de internetverbinding, en verschillende klachten van onze klanten (voornamelijk over de snelheid en regelmatig verlies van de verbinding). Besloten we advies te vragen bij Sterknetwerk. Zij kwamen met een duidelijk voorstel en binnen de kortste tijd lag er een nieuwe internetlijn. Sindsdien hebben we geen klachten meer gehad, en kan iedereen probleemloos werken.")

Question.create!(title: "Heeft u overal en altijd toegang tot uw e-mail en agenda (mobiele telefoon / webmail)?", indicator: Indicator.where(title: "Apparaat synchronisatie").first, aspect: Aspect.where(title: "Mogelijkheden").first)